###
GET http://localhost:8080/api/process/finished

###
POST http://localhost:8080/api/process/finished
Content-Type: application/json

{
  "title": "one",
  "finishedStages": [
    {
      "prompt": "which is which?",
      "answer": "",
      "finishedChoices": [
        {
          "text": "a",
          "value": "true"
        },
        {
          "text": "b",
          "value": "false"
        },
        {
          "text": "c",
          "value": "false"
        },
        {
          "text": "d",
          "value": "true"
        }
      ]
    }
  ]
}