###
GET http://localhost:8080/api/process

}

###
POST http://localhost:8080/api/process
Content-Type: application/json

{
  "title": "one",
  "stage": [{
    "prompt": "which is which?",
    "type": "choice",
    "choice": ["a", "b", "c", "d"]
    }]
}

###
POST http://localhost:8080/api/process
Content-Type: application/json

{
  "title": "two",
  "stage": [{
    "prompt": "where is where?",
    "type": "boolean",
    "choice": []
    },
    {
    "prompt": "who is who?",
    "type": "text",
    "choice": []
    }]
}

